name: Build and Publish I2PD

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs every day at 0 AM UTC

permissions:
  contents: write
  packages: write

jobs:
  check-base-packages:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check_changes.outputs.changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
      - name: Pull base image and upgrade to check for changes
        run: |
          docker pull alpine:latest
          echo "FROM alpine:latest" > Dockerfile.temp
          echo "RUN apk update && apk upgrade && apk add --no-cache \\" >> Dockerfile.temp
          echo "    build-base \\" >> Dockerfile.temp
          echo "    cmake \\" >> Dockerfile.temp
          echo "    git \\" >> Dockerfile.temp
          echo "    linux-headers \\" >> Dockerfile.temp
          echo "    openssl-dev \\" >> Dockerfile.temp
          echo "    zlib-dev \\" >> Dockerfile.temp
          echo "    boost-dev \\" >> Dockerfile.temp
          echo "    miniupnpc-dev \\" >> Dockerfile.temp
          echo "    samurai" >> Dockerfile.temp
          docker build -f Dockerfile.temp -t temp-check-image .
          docker run --rm temp-check-image apk info -v build-base cmake git linux-headers openssl-dev zlib-dev boost-dev miniupnpc-dev samurai | sort > current-packages.txt
          rm Dockerfile.temp
      - name: Compare with stored package list
        id: check_changes
        run: |
          if [ ! -f package-versions.txt ]; then
            echo "package-versions.txt does not exist, treating as changed"
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            grep -vE "^(i2pd-|mimalloc-|#)" package-versions.txt | grep -v "^$" | sort > stored-packages.txt
            if ! cmp -s stored-packages.txt current-packages.txt; then
              echo "Package list has changed."
              echo "changed=true" >> $GITHUB_OUTPUT
            else
              echo "Package list has not changed."
              echo "changed=false" >> $GITHUB_OUTPUT
            fi
          fi

  check-versions:
    runs-on: ubuntu-latest
    outputs:
      new_version_detected: ${{ steps.check.outputs.new_version_detected }}
      latest_tag: ${{ steps.get_latest_release.outputs.tag }}
      latest_mimalloc_tag: ${{ steps.get_latest_mimalloc.outputs.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get latest i2pd commit
        id: get_latest_release
        run: |
          LATEST_TAG=$(git ls-remote --tags --sort='v:refname' https://github.com/PurpleI2P/i2pd.git | grep "refs/tags/2" | grep -v "\^{}" | tail -n1 | sed 's/.*\///')
          echo "tag=${LATEST_TAG}" >> $GITHUB_OUTPUT
      - name: Get latest mimalloc tag
        id: get_latest_mimalloc
        run: |
          LATEST_TAG=$(git ls-remote --tags --sort='v:refname' https://github.com/microsoft/mimalloc.git | grep "refs/tags/v" | tail -n1 | sed 's/.*\///' | sed 's/\^{}//')
          echo "tag=${LATEST_TAG}" >> $GITHUB_OUTPUT
      - name: Get current versions from package-versions.txt
        id: get_current_version
        run: |
          echo "version=$(grep "^i2pd-" package-versions.txt | cut -d- -f2)" >> $GITHUB_OUTPUT
          echo "mimalloc_version=$(grep "^mimalloc-" package-versions.txt | cut -d- -f2 || echo "")" >> $GITHUB_OUTPUT
      - name: Check for new version
        id: check
        run: |
          if [[ "${{ steps.get_latest_release.outputs.tag }}" != "" && "${{ steps.get_latest_release.outputs.tag }}" != "${{ steps.get_current_version.outputs.version }}" ]]; then
            echo "new_version_detected=true" >> $GITHUB_OUTPUT
          elif [[ "${{ steps.get_latest_mimalloc.outputs.tag }}" != "" && "${{ steps.get_latest_mimalloc.outputs.tag }}" != "${{ steps.get_current_version.outputs.mimalloc_version }}" ]]; then
            echo "new_version_detected=true" >> $GITHUB_OUTPUT
          else
            echo "new_version_detected=false" >> $GITHUB_OUTPUT
          fi

  build-images:
    needs: [check-base-packages, check-versions]
    if: needs.check-base-packages.outputs.changed == 'true' || needs.check-versions.outputs.new_version_detected == 'true' || github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-latest
            tag_suffix: amd64-alpine-static
            variant: generic
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
            tag_suffix: arm64-alpine-static
            variant: generic
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push I2PD (${{ matrix.tag_suffix }})
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          file: docker/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          provenance: false
          build-args: |
            I2PD_VERSION=${{ needs.check-versions.outputs.latest_tag }}
            MIMALLOC_VERSION=${{ needs.check-versions.outputs.latest_mimalloc_tag }}
            ARM64_VARIANT=${{ matrix.variant }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/i2pd:${{ matrix.tag_suffix }}
          cache-from: type=gha,scope=build-${{ matrix.tag_suffix }}
          cache-to: type=gha,mode=min,scope=build-${{ matrix.tag_suffix }}

  merge-tags:
    needs: [build-images]
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create and push manifest for branch
        run: |
          docker buildx imagetools create -t ghcr.io/${{ github.repository_owner }}/i2pd:alpine-static \
            ghcr.io/${{ github.repository_owner }}/i2pd:amd64-alpine-static \
            ghcr.io/${{ github.repository_owner }}/i2pd:arm64-alpine-static

  update-repo:
    needs: [check-base-packages, check-versions, build-images, merge-tags]
    if: needs.check-base-packages.outputs.changed == 'true' || needs.check-versions.outputs.new_version_detected == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update version and package files and commit
        run: |
          if [ "${{ needs.check-base-packages.outputs.changed }}" = "true" ]; then
          echo "FROM alpine:latest" > Dockerfile.temp
          echo "RUN apk update && apk upgrade && apk add --no-cache \\" >> Dockerfile.temp
          echo "    build-base \\" >> Dockerfile.temp
          echo "    cmake \\" >> Dockerfile.temp
          echo "    git \\" >> Dockerfile.temp
          echo "    linux-headers \\" >> Dockerfile.temp
          echo "    openssl-dev \\" >> Dockerfile.temp
          echo "    zlib-dev \\" >> Dockerfile.temp
          echo "    boost-dev \\" >> Dockerfile.temp
          echo "    miniupnpc-dev \\" >> Dockerfile.temp
          echo "    samurai" >> Dockerfile.temp
            docker build -f Dockerfile.temp -t temp-check-image-commit .
            docker run --rm temp-check-image-commit apk info -v build-base cmake git linux-headers openssl-dev zlib-dev boost-dev miniupnpc-dev samurai | sort > packages-temp.txt
            rm Dockerfile.temp
            docker rmi -f temp-check-image-commit
          fi

          if [ "${{ needs.check-base-packages.outputs.changed }}" = "true" ]; then
             LATEST_I2PD="${{ needs.check-versions.outputs.latest_tag }}"
             MIMALLOC_VER="${{ needs.check-versions.outputs.latest_mimalloc_tag }}"
             echo "# Main Application Versions" > package-versions.txt
             echo "i2pd-${LATEST_I2PD}" >> package-versions.txt
             echo "mimalloc-${MIMALLOC_VER}" >> package-versions.txt
             echo "" >> package-versions.txt
             echo "# Build Dependencies (Alpine Edge)" >> package-versions.txt
             echo "# These are used for static linking" >> package-versions.txt
             cat packages-temp.txt >> package-versions.txt
             rm packages-temp.txt
          else
             LATEST_I2PD="${{ needs.check-versions.outputs.latest_tag }}"
             MIMALLOC_VER="${{ needs.check-versions.outputs.latest_mimalloc_tag }}"
             sed -i "s/^i2pd-.*/i2pd-${LATEST_I2PD}/" package-versions.txt
             if grep -q "^mimalloc-" package-versions.txt; then
               sed -i "s/^mimalloc-.*/mimalloc-${MIMALLOC_VER}/" package-versions.txt
             else
               echo "mimalloc-${MIMALLOC_VER}" >> package-versions.txt
             fi
          fi
          
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add package-versions.txt
          if ! git diff --staged --quiet; then
            git commit -m "ci: Update i2pd version and package list"
            git pull --rebase
            git push
          fi
